# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent_kernel._proto import kernel_pb2 as kernel__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kernel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Meta = channel.unary_unary(
                '/agentkernel.v1.PluginService/Meta',
                request_serializer=kernel__pb2.Empty.SerializeToString,
                response_deserializer=kernel__pb2.PluginMeta.FromString,
                _registered_method=True)
        self.Handshake = channel.unary_unary(
                '/agentkernel.v1.PluginService/Handshake',
                request_serializer=kernel__pb2.HandshakeReq.SerializeToString,
                response_deserializer=kernel__pb2.HandshakeResp.FromString,
                _registered_method=True)
        self.Init = channel.unary_unary(
                '/agentkernel.v1.PluginService/Init',
                request_serializer=kernel__pb2.InitReq.SerializeToString,
                response_deserializer=kernel__pb2.InitResp.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/agentkernel.v1.PluginService/Start',
                request_serializer=kernel__pb2.Empty.SerializeToString,
                response_deserializer=kernel__pb2.Empty.FromString,
                _registered_method=True)
        self.OnEvent = channel.unary_unary(
                '/agentkernel.v1.PluginService/OnEvent',
                request_serializer=kernel__pb2.Envelope.SerializeToString,
                response_deserializer=kernel__pb2.Envelope.FromString,
                _registered_method=True)
        self.Snapshot = channel.unary_unary(
                '/agentkernel.v1.PluginService/Snapshot',
                request_serializer=kernel__pb2.Empty.SerializeToString,
                response_deserializer=kernel__pb2.SnapshotResp.FromString,
                _registered_method=True)
        self.Restore = channel.unary_unary(
                '/agentkernel.v1.PluginService/Restore',
                request_serializer=kernel__pb2.SnapshotReq.SerializeToString,
                response_deserializer=kernel__pb2.Empty.FromString,
                _registered_method=True)
        self.Drain = channel.unary_unary(
                '/agentkernel.v1.PluginService/Drain',
                request_serializer=kernel__pb2.DrainReq.SerializeToString,
                response_deserializer=kernel__pb2.DrainResp.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/agentkernel.v1.PluginService/Stop',
                request_serializer=kernel__pb2.Empty.SerializeToString,
                response_deserializer=kernel__pb2.Empty.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/agentkernel.v1.PluginService/Destroy',
                request_serializer=kernel__pb2.Empty.SerializeToString,
                response_deserializer=kernel__pb2.Empty.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/agentkernel.v1.PluginService/Health',
                request_serializer=kernel__pb2.Empty.SerializeToString,
                response_deserializer=kernel__pb2.HealthResp.FromString,
                _registered_method=True)


class PluginServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Meta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Handshake(self, request, context):
        """ApiVersion 协商
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnEvent(self, request, context):
        """M1 语义为一请求一响应（请求/回复经 idempotency_key 关联）。
        说明：原设计为双向流，但跨运行时（tonic ↔ grpc-python / grpc-js）的
        流式互操作在实测中不可靠（DATA 帧未送达）。需要真正的流式语义
        （如 LLM token 流）时，再新增 OnEventStream 双向流 RPC。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Snapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Restore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Meta': grpc.unary_unary_rpc_method_handler(
                    servicer.Meta,
                    request_deserializer=kernel__pb2.Empty.FromString,
                    response_serializer=kernel__pb2.PluginMeta.SerializeToString,
            ),
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=kernel__pb2.HandshakeReq.FromString,
                    response_serializer=kernel__pb2.HandshakeResp.SerializeToString,
            ),
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=kernel__pb2.InitReq.FromString,
                    response_serializer=kernel__pb2.InitResp.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=kernel__pb2.Empty.FromString,
                    response_serializer=kernel__pb2.Empty.SerializeToString,
            ),
            'OnEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.OnEvent,
                    request_deserializer=kernel__pb2.Envelope.FromString,
                    response_serializer=kernel__pb2.Envelope.SerializeToString,
            ),
            'Snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=kernel__pb2.Empty.FromString,
                    response_serializer=kernel__pb2.SnapshotResp.SerializeToString,
            ),
            'Restore': grpc.unary_unary_rpc_method_handler(
                    servicer.Restore,
                    request_deserializer=kernel__pb2.SnapshotReq.FromString,
                    response_serializer=kernel__pb2.Empty.SerializeToString,
            ),
            'Drain': grpc.unary_unary_rpc_method_handler(
                    servicer.Drain,
                    request_deserializer=kernel__pb2.DrainReq.FromString,
                    response_serializer=kernel__pb2.DrainResp.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=kernel__pb2.Empty.FromString,
                    response_serializer=kernel__pb2.Empty.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=kernel__pb2.Empty.FromString,
                    response_serializer=kernel__pb2.Empty.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=kernel__pb2.Empty.FromString,
                    response_serializer=kernel__pb2.HealthResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentkernel.v1.PluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentkernel.v1.PluginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Meta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentkernel.v1.PluginService/Meta',
            kernel__pb2.Empty.SerializeToString,
            kernel__pb2.PluginMeta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentkernel.v1.PluginService/Handshake',
            kernel__pb2.HandshakeReq.SerializeToString,
            kernel__pb2.HandshakeResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentkernel.v1.PluginService/Init',
            kernel__pb2.InitReq.SerializeToString,
            kernel__pb2.InitResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentkernel.v1.PluginService/Start',
            kernel__pb2.Empty.SerializeToString,
            kernel__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentkernel.v1.PluginService/OnEvent',
            kernel__pb2.Envelope.SerializeToString,
            kernel__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentkernel.v1.PluginService/Snapshot',
            kernel__pb2.Empty.SerializeToString,
            kernel__pb2.SnapshotResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Restore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentkernel.v1.PluginService/Restore',
            kernel__pb2.SnapshotReq.SerializeToString,
            kernel__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentkernel.v1.PluginService/Drain',
            kernel__pb2.DrainReq.SerializeToString,
            kernel__pb2.DrainResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentkernel.v1.PluginService/Stop',
            kernel__pb2.Empty.SerializeToString,
            kernel__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentkernel.v1.PluginService/Destroy',
            kernel__pb2.Empty.SerializeToString,
            kernel__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentkernel.v1.PluginService/Health',
            kernel__pb2.Empty.SerializeToString,
            kernel__pb2.HealthResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
